### ISSUE TITLE
Keyboard shortcut label wrong

### ISSUE THREAD

**Issue by uwegeercken** [twineworks/tweakstreet-issues#22] opened 2020-08-25 06:35 UTC
### Description

In the UI the keyboard shortcut for "Zoom in" is labeled as "Ctrl + =" where as it really is "Ctrl + +"

### Expected behavior

Change the keyboard shortcut label appropriately

**Comment by slawo-ch** [comment] 2020-08-25 09:10
Duplicate of #17 

Please reopen with more details if this issue is about another shortcut.

**Closed as completed by slawo-ch** 2020-08-25 09:10 UTC
