### ISSUE TITLE
Add step: filter enhancements

### ISSUE THREAD

**Issue by uwegeercken** [twineworks/tweakstreet-issues#33] opened 2020-09-09 12:02 UTC
### Problem description

The filtering of the steps when one types in characters does not work good in some cases.

E.g. typing "c-r-e-a-t-e" shows besides others "Stateful Calculator" and marks as follwos: **C**alculato**r** with the **a**bili**t**y to build int**e**rnal state. The selection of these single characters seems odd. In this example the "Look ahead/behind" step is also listed.

Another example is "d-a-t-a". It shows also the "Sleep" step and marks: **D**el**a**ys each inpu**t** row for **a** time. "Sleep" should not appear when doing a search for "data" and again the selection of single characters from the description of the step seems odd. Or maybe the display of bold characters does not work correctly.

Another example is typing: "f-i-l-t-e". At this point there are many steps listed related to "file/files".

### Preferred solution

The logic should list only those steps that have the typed in characters in their description or name. Don't list those steps where all characters are present but are single characters.

**Comment by slawo-ch** [comment] 2020-10-06 10:09
The purpose of putting partial matches into the results is to allow people to search using incomplete or possibly slightly mistyped sequences.

For example if you're looking for the mongodb insert step, you type 'monins' and the step will appear in the results near the top. Sporadic non-consecutive matches will be below.

The search results are scored such that consecutive letter matches appear at the top. Sporadic matches are less relevant and are listed below. 
 
This is the intended behaviour. Closing this off for now. Please reopen if you find that the actual behavior deviates from intended as explained above.

**Closed as completed by slawo-ch** 2020-10-06 10:09 UTC
